# Android
# Build your Android project with Gradle.
# Add steps that test, sign, and distribute the APK, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/android

pool:
  vmImage: 'macOS 10.13'

steps:
- task: InstallAppleCertificate@2
  inputs:
    certSecureFile: 'aCertificates.p12'
    certPwd: 'Rebus@123'

- task: InstallAppleProvisioningProfile@1
  inputs:
    provProfileSecureFile: 'RebusAEMM.mobileprovision'

- task: NodeTool@0
  inputs:
    versionSpec: '8.x'
  displayName: 'Install Node.js'

- script: |
    npm install
    yarn install
    export LC_ALL=en_US.UTF-8
    export LANG=en_US.UTF-8
  displayName: 'npm install dependencies'

- task: Xcode@5
  inputs:
    workingDirectory: '$(system.defaultWorkingDirectory)/ios'
    actions: 'build'
    scheme: ''
    sdk: 'iphoneos'
    configuration: 'Release'
    xcWorkspacePath: '$(system.defaultWorkingDirectory)/ios/ReactNJenkin.xcodeproj'
    exportOptions: 'auto'
    signingOption: 'auto' 
    signingIdentity: 'Rebus Mobility (3TZF4QK823)'
    provisioningProfileUuid: '56b2f86a-7e7d-4209-959c-b76032569920'
    provisioningProfileName: '56b2f86a-7e7d-4209-959c-b76032569920.mobileprovision'
    teamId: '5JR7LRDRL9'
    xcodeVersion: '10' 
    useXcpretty: true

- task: CopyFiles@2
  inputs:
    contents: '**/*.ipa'
    targetFolder: '$(build.artifactStagingDirectory)'


- task: AppCenterDistribute@1
  inputs:
    serverEndpoint: MyAppcenter
    appSlug: MohsinTest/ReactAzureTesiOS
    appFile: $(build.artifactstagingdirectory)/**/*.ipa
    #symbolsOption: 'Apple' # Optional. Options: apple
    #symbolsPath: # Optional
    #symbolsPdbFiles: '**/*.pdb' # Optional
    #symbolsDsymFiles: # Optional
    #symbolsMappingTxtFile: # Optional
    #symbolsIncludeParentDirectory: # Optional
    #releaseNotesOption: 'input' # Options: input, file
    #releaseNotesInput: # Required when releaseNotesOption == Input
    #releaseNotesFile: # Required when releaseNotesOption == File
    #isMandatory: false # Optional
    #distributionGroupId: # Optional