# Node.js with React
# Build a Node.js project that uses React.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool:
  vmImage: 'macOS 10.13'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '8.x'
  displayName: 'Install Node.js'

- script: |
    npm install
  displayName: 'npm install dependencies'

- script: npm run lint
  displayName: 'Run lint'
- script: npm run test
  displayName: 'Run unit tests'

- script: |
    cd android
    fastlane beta
  displayName: 'Build android'