pool:
  vmImage: 'macOS 10.13'

steps:
- task: InstallAppleCertificate@2
  inputs:
    certSecureFile: 'aCertificates.p12'
    certPwd: 'Rebus@123'

- task: InstallAppleProvisioningProfile@1
  inputs:
    provProfileSecureFile: '56b2f86a-7e7d-4209-959c-b76032569920.mobileprovision'

- task: NodeTool@0
  inputs:
    versionSpec: '8.x'
  displayName: 'Install Node.js'

- script: |
    xcodebuild -showsdks
    npm install
    yarn install
    react-native bundle --platform ios --dev false --entry-file index.js --bundle-output iOS/main.jsbundle
    export LC_ALL=en_US.UTF-8
    export LANG=en_US.UTF-8
  displayName: 'npm install dependencies'

- task: Gradle@2
  inputs:
    workingDirectory: '$(system.defaultWorkingDirectory)/android'
    gradleWrapperFile: '$(system.defaultWorkingDirectory)/android/gradlew'
    gradleOptions: '-Xmx3072m'
    publishJUnitResults: false
    testResultsFiles: '**/TEST-*.xml'
    tasks: 'assembleRelease'

- task: CopyFiles@2
  inputs:
    contents: '**/*.apk'
    targetFolder: '$(build.artifactStagingDirectory)'

- task: PublishBuildArtifacts@1
  inputs:
    pathToPublish: '$(build.artifactStagingDirectory)'
    artifactName: 'drop'
    artifactType: 'container'
  
- task: AndroidSigning@2
  inputs:
    apkFiles: '**/*.apk'
    jarsign: true
    jarsignerKeystoreFile: 'my-release-key.keystore'
    jarsignerKeystorePassword: 'threeuk'
    jarsignerKeystoreAlias: 'my-key-alias'
    jarsignerKeyPassword: 'threeuk'
    zipalign: true

- task: AppCenterDistribute@2
  displayName: 'Deploy to Visual Studio App Center'
  inputs:
    serverEndpoint: 'MyAppcenter'
    appSlug: MohsinTest/ReactAzureTest
    appFile: 'android/app/build/outputs/apk/release/app-release-unsigned.apk'
    symbolsIncludeParentDirectory: false
    releaseNotesInput: 'Azure devops to app center'

- task: Xcode@5
  inputs:
    actions: 'build'
    scheme: ''
    sdk: 'iphoneos11.4'
    configuration: 'Debug'
    xcWorkspacePath: '$(system.defaultWorkingDirectory)/ios/ReactNJenkin.xcodeproj'
    exportMethod: 'ad-hoc'
    signingOption: 'manual' 
    signingIdentity: '$(APPLE_CERTIFICATE_SIGNING_IDENTITY)'
    provisioningProfileUuid: '$(APPLE_PROV_PROFILE_UUID)'
    xcodeVersion: 'default' 
    useXcpretty: true
    

