# Android
# Build your Android project with Gradle.
# Add steps that test, sign, and distribute the APK, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/android

pool:
  vmImage: 'macOS 10.13'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '8.x'
  displayName: 'Install Node.js'

- script: |
    npm install
    export LC_ALL=en_US.UTF-8
    export LANG=en_US.UTF-8
  displayName: 'npm install dependencies'

- task: Gradle@2
  inputs:
    workingDirectory: '$(system.defaultWorkingDirectory)/android'
    gradleWrapperFile: '$(system.defaultWorkingDirectory)/android/gradlew'
    gradleOptions: '-Xmx3072m'
    publishJUnitResults: false
    testResultsFiles: '**/TEST-*.xml'
    tasks: 'assembleRelease'

- task: CopyFiles@2
  inputs:
    contents: '**/*.apk'
    targetFolder: '$(build.artifactStagingDirectory)'

- task: PublishBuildArtifacts@1
  inputs:
    pathToPublish: '$(build.artifactStagingDirectory)'
    artifactName: 'drop'
    artifactType: 'container'
  
- task: AndroidSigning@2
  inputs:
    apkFiles: '**/*.apk'
    jarsign: true
    jarsignerKeystoreFile: 'my-release-key.keystore'
    jarsignerKeystorePassword: 'threeuk'
    jarsignerKeystoreAlias: 'my-key-alias'
    jarsignerKeyPassword: 'threeuk'
    zipalign: true

- task: AppCenterTest@1
  inputs:
    appFile: 'android/app/build/outputs/apk/release/app-release-unsigned.apk' 
    artifactsDirectory: '$(build.artifactStagingDirectory)/AppCenterTest' 
    prepareTests: true
    frameworkOption: uitest
    uiTestBuildDirectory: $(build.artifactStagingDirectory)/test

- task: AppCenterDistribute@2
  displayName: 'Deploy to Visual Studio App Center'
  inputs:
    serverEndpoint: 'MyAppcenter'
    appSlug: MohsinTest/ReactAzureTest
    appFile: 'android/app/build/outputs/apk/release/app-release-unsigned.apk'
    symbolsIncludeParentDirectory: false
    releaseNotesInput: 'Azure devops to app center'